version: '3.8'
services:
  app:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - ./client:/usr/src/app/client
    environment:
      - NODE_ENV=development
